"""Report generation — Phase 1 (Discovery & Inventory) and Phase 2 (Gap Assessment).

Self-contained HTML (no external assets) + JSON export. The disclaimer from
docs/DISCLAIMER.md ships in every report.
"""
from __future__ import annotations

import html
import json

from .engine import summarize
from .workspace import REPO_ROOT, client_dir, load_json, list_snapshots

STATUS_COLORS = {"COMPLIANT": "#1a7f37", "PARTIAL": "#b58900", "GAP": "#c62828",
                 "NA": "#607d8b", "TBC": "#5c6bc0"}
STATUS_LABELS = {"COMPLIANT": "Compliant", "PARTIAL": "Partial", "GAP": "Gap",
                 "NA": "Not applicable", "TBC": "To be confirmed"}

_CSS = """
body{font-family:Segoe UI,system-ui,sans-serif;margin:0;background:#f6f7f9;color:#1c2733}
.wrap{max-width:1080px;margin:0 auto;padding:24px}
header{background:#0d2137;color:#fff;padding:28px 0}
header .wrap{padding-top:0;padding-bottom:0}
h1{margin:0 0 4px;font-size:26px} h2{margin-top:36px;border-bottom:2px solid #dde3ea;padding-bottom:6px}
.sub{color:#9fb3c8;font-size:14px}
table{border-collapse:collapse;width:100%;background:#fff;font-size:14px;margin:12px 0}
th,td{border:1px solid #dde3ea;padding:8px 10px;text-align:left;vertical-align:top}
th{background:#eef2f6}
.badge{display:inline-block;padding:2px 10px;border-radius:12px;color:#fff;font-size:12px;font-weight:600;white-space:nowrap}
.sev{font-size:11px;text-transform:uppercase;color:#607d8b;font-weight:700}
.ev{font-size:12px;color:#44576b;background:#f0f4f8;border-left:3px solid #b0c4d8;padding:6px 8px;margin:4px 0;word-break:break-word}
.score{font-size:44px;font-weight:700}
.cards{display:flex;gap:14px;flex-wrap:wrap;margin:16px 0}
.card{background:#fff;border:1px solid #dde3ea;border-radius:8px;padding:14px 20px;min-width:120px}
.card .n{font-size:30px;font-weight:700}
.disclaimer{background:#fff8e6;border:1px solid #e6d9a8;border-radius:8px;padding:14px 18px;font-size:13px;margin:28px 0}
.small{font-size:12px;color:#607d8b}
.assist{color:#1a7f37;font-size:12px}
.conflict{color:#c62828;font-size:12px;font-weight:600}
.overflow{overflow-x:auto}
"""


def _e(s) -> str:
    return html.escape(str(s if s is not None else ""))


def _badge(status: str) -> str:
    return f'<span class="badge" style="background:{STATUS_COLORS[status]}">{STATUS_LABELS[status]}</span>'


def _disclaimer_html() -> str:
    text = (REPO_ROOT / "docs" / "DISCLAIMER.md").read_text(encoding="utf-8")
    body = text.split("---", 1)[-1].strip()
    paras = "".join(f"<p>{_e(p.strip())}</p>" for p in body.split("\n\n") if p.strip())
    return f'<div class="disclaimer"><strong>Disclaimer & terms of engagement</strong>{paras}</div>'


def _page(title: str, client: str, snapshot: dict, body: str) -> str:
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>{_e(title)} — {_e(client)}</title><style>{_CSS}</style></head><body>
<header><div class="wrap"><h1>{_e(title)}</h1>
<div class="sub">{_e(client)} · scan {_e(snapshot['scanId'])} · rulebook v{_e(snapshot['rulebookVersion'])} ·
generated by DPDPA Sentinel</div></div></header>
<div class="wrap">{body}{_disclaimer_html()}
<p class="small">Evidence excerpts are PII-masked before storage. Snapshot file: scans/{_e(snapshot['scanId'])}.json</p>
</div></body></html>"""


def phase1_html(snapshot: dict) -> str:
    meta = snapshot.get("meta", {})
    rows_pages = "".join(
        f"<tr><td>{_e(p['site'])}</td><td>{_e(p['page'])}</td><td>{_e(p['url'])}</td>"
        f"<td>{_e(p.get('status') or p.get('error'))}</td></tr>"
        for p in meta.get("pagesScanned", []))
    rows_trk = "".join(
        f"<tr><td>{_e(site)}</td><td>{_e(', '.join(t) or '—')}</td>"
        f"<td>{_e(', '.join(meta.get('cookiesObserved', {}).get(site, [])) or '—')}</td>"
        f"<td>{_e(', '.join(meta.get('cmpObserved', {}).get(site, [])) or 'NONE DETECTED')}</td></tr>"
        for site, t in meta.get("trackersObserved", {}).items())
    rows_forms = "".join(
        f"<tr><td>{_e(f['page'])}</td><td>{_e(f['personalDataFields'])}</td>"
        f"<td>{'Yes' if f['consentControl'] else '<b>No</b>'}</td></tr>"
        for f in meta.get("formsFound", []))
    rows_dept = "".join(
        f"<tr><td>{_e(d['department'])}</td><td>{_e(', '.join(d['partsAnswered']) or '—')}</td>"
        f"<td>{_e(', '.join(d['partsPending']) or '—')}</td></tr>"
        for d in snapshot.get("departmentCoverage", []))
    warnings = "".join(f"<li>{_e(w)}</li>" for w in snapshot.get("warnings", []))

    body = f"""
<h2>1. Scan surface</h2>
<div class="overflow"><table><tr><th>Site</th><th>Page</th><th>URL</th><th>HTTP status</th></tr>{rows_pages or '<tr><td colspan=4>web scan skipped</td></tr>'}</table></div>
<h2>2. Observed third parties, cookies and consent tooling</h2>
<div class="overflow"><table><tr><th>Site</th><th>Trackers observed</th><th>Cookies on first request</th><th>Consent platform (CMP)</th></tr>{rows_trk or '<tr><td colspan=4>web scan skipped</td></tr>'}</table></div>
<h2>3. Data-collection forms discovered</h2>
<div class="overflow"><table><tr><th>Page</th><th>Personal-data fields</th><th>Consent control present</th></tr>{rows_forms or '<tr><td colspan=3>No static forms found — JavaScript-rendered forms require browser-mode scan (roadmap)</td></tr>'}</table></div>
<h2>4. Departmental questionnaire coverage</h2>
<div class="overflow"><table><tr><th>Department</th><th>Parts answered</th><th>Parts pending</th></tr>{rows_dept or '<tr><td colspan=3>No departmental questionnaires imported yet</td></tr>'}</table></div>
{f'<h2>Warnings</h2><ul>{warnings}</ul>' if warnings else ''}
"""
    return _page("Phase 1 — Discovery & Inventory", snapshot["client"], snapshot, body)


def phase2_html(snapshot: dict) -> str:
    s = summarize(snapshot)
    cards = "".join(
        f'<div class="card"><div class="n" style="color:{STATUS_COLORS[k]}">{v}</div>{STATUS_LABELS[k]}</div>'
        for k, v in s["counts"].items())
    cat_rows = "".join(
        f"<tr><td>{_e(cat)}</td>" + "".join(f"<td>{c[k] or ''}</td>" for k in
        ("COMPLIANT", "PARTIAL", "GAP", "NA", "TBC")) + "</tr>"
        for cat, c in sorted(s["byCategory"].items()))

    sections = []
    order = {"GAP": 0, "PARTIAL": 1, "TBC": 2, "COMPLIANT": 3, "NA": 4}
    sev_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    for r in sorted(snapshot["resolutions"], key=lambda r: (order[r["status"]], sev_order[r["severity"]])):
        evs = "".join(
            f'<div class="ev"><b>{_e(e.get("kind"))}</b> {_e(e.get("url", ""))} · {_e(e.get("observedAt", ""))}'
            + (f'<br>{_e(e.get("excerpt"))}' if e.get("excerpt") else "")
            + (f'<br>headers: {_e(e.get("headers"))}' if e.get("headers") else "")
            + (f'<br><i>{_e(e.get("note"))}</i>' if e.get("note") else "")
            + (f'<br>sha256: <code>{_e(e.get("sha256"))}</code>' if e.get("sha256") else "")
            + "</div>"
            for e in r["evidence"])
        assist = r.get("appAssist", {})
        assist_html = (f'<div class="assist">✔ This tool can assist: {_e(assist.get("how"))} '
                       f'<i>(runs only with client consent, access and permission)</i></div>'
                       if assist.get("possible") and r["status"] in ("GAP", "PARTIAL", "TBC") else "")
        conflict = f'<div class="conflict">⚠ {_e(r["conflict"])}</div>' if r.get("conflict") else ""
        remediation = (f'<div class="small"><b>Recommendation:</b> {_e(r["remediation"])}</div>'
                       if r["status"] in ("GAP", "PARTIAL", "TBC") else "")
        sections.append(f"""
<tr><td><b>{_e(r['controlId'])}</b><br><span class="sev">{_e(r['severity'])}</span></td>
<td><b>{_e(r['title'])}</b><div class="small">{_e(r['legalRef'])} · basis: {_e(r['basis'])}</div>
{conflict}{evs}{remediation}{assist_html}</td>
<td>{_badge(r['status'])}</td></tr>""")

    body = f"""
<h2>Compliance scorecard</h2>
<div class="cards"><div class="card"><div class="score">{s['complianceScore']}%</div>
<div class="small">of determined checkpoints<br>(compliant + ½·partial)</div></div>{cards}</div>
<div class="overflow"><table><tr><th>Category</th><th>Compliant</th><th>Partial</th><th>Gap</th><th>N/A</th><th>TBC</th></tr>{cat_rows}</table></div>
<h2>Checkpoint detail — gaps first, with evidence</h2>
<div class="overflow"><table><tr><th style="width:90px">Control</th><th>Checkpoint, evidence & recommendation</th><th style="width:130px">Status</th></tr>
{''.join(sections)}</table></div>
"""
    return _page("Phase 2 — Gap Assessment", snapshot["client"], snapshot, body)


def generate(slug: str, snapshot: dict | None = None) -> list[str]:
    if snapshot is None:
        snaps = list_snapshots(slug)
        if not snaps:
            raise FileNotFoundError("No scan snapshots — run: dpdpa scan")
        snapshot = load_json(snaps[-1])
    outdir = client_dir(slug) / "reports"
    outdir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, content in (("phase1-discovery.html", phase1_html(snapshot)),
                          ("phase2-gap-assessment.html", phase2_html(snapshot))):
        p = outdir / name
        p.write_text(content, encoding="utf-8")
        written.append(str(p))
    summary = {"client": snapshot["client"], "scanId": snapshot["scanId"],
               "rulebookVersion": snapshot["rulebookVersion"], **summarize(snapshot),
               "gaps": [{"id": r["controlId"], "title": r["title"], "severity": r["severity"],
                          "appAssist": r.get("appAssist", {}).get("possible", False)}
                         for r in snapshot["resolutions"] if r["status"] == "GAP"]}
    p = outdir / "summary.json"
    p.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    written.append(str(p))
    from . import report_premium
    written.append(report_premium.generate(slug, snapshot))
    return written
