"""ai_suggestions table

Revision ID: 144f5e885eb4
Revises: ee0001f68184
Create Date: 2026-08-09 00:02:06.315311
"""
from alembic import op
import sqlalchemy as sa


revision = '144f5e885eb4'
down_revision = 'ee0001f68184'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('batch', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_suggestions_batch'), 'ai_suggestions', ['batch'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_company_id'), 'ai_suggestions', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_suggestions_company_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_suggestions_batch'), table_name='ai_suggestions')
    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
