"""monitoring fields

Revision ID: b734d8781bca
Revises: 144f5e885eb4
Create Date: 2026-08-09 00:46:08.644518
"""
from alembic import op
import sqlalchemy as sa


revision = 'b734d8781bca'
down_revision = '144f5e885eb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('monitor_frequency', sa.String(length=12),
                                          nullable=False, server_default='off'))
    op.add_column('companies', sa.Column('next_monitor_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'next_monitor_at')
    op.drop_column('companies', 'monitor_frequency')
    # ### end Alembic commands ###
